version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/pkg"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"
