#!/usr/bin/env bash
####################################################################################################
# Copyright © 2023 Bahman Movaqar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
####################################################################################################

set -o errexit
set -o pipefail

source ${root_dir}tests/lib.sh

####################################################################################################
# run_all_test_suites
#
# Globals:
#   tests_to_run
#
# Output:
#   PASSED_TEST_COUNT FAILED_TEST_COUNT
####################################################################################################
function run_all_test_suites {
  local failed_count=0
  local ok_count=0

  echo
  for t in $tests_to_run; do
    if bmakelib.test.run_test_suite $t; then
      ok_count=$(( $ok_count + 1 ))
    else
      failed_count=$(( $failed_count + 1 ))
    fi
    echo
  done

  echo
  echo "✅ $ok_count test suite(s) passed."
  [[ $failed_count -ne 0 ]] && echo "❌ $failed_count test suite(s) failed."
  [[ $failed_count -eq 0 ]] || return 1
}

# list of absolute paths
tests_to_run=${RUNNER_TESTS}
if [[ -z "$tests_to_run" ]]; then
  bmakelib.test.echo.error 'runner: No tests to run specificed - set the value of RUNNER_TESTS.'
  exit 1
fi

# absolute path
export target_dir=${RUNNER_DIR}
if [[ -z "$target_dir" ]]; then
  bmakelib.test.echo.error 'runner: No target (temp) directory sepcified - set the value of RUNNER_DIR.'
  exit 1
fi

export root_dir=${RUNNER_ROOT}
if [[ -z "$root_dir" ]]; then
  bmakelib.test.echo.error 'runner: No bmakelib root directory sepcified - set the value of RUNNER_ROOT.'
  exit 1
fi

run_all_test_suites
