#!/usr/bin/env bash
####################################################################################################
# Copyright © Bahman Movaqar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
####################################################################################################

set -o pipefail

test_suite_name=$(basename $BASH_SOURCE)
source ${root_dir}tests/lib.sh

####################################################################################################
# When a dictionary is defined, happy-path put and get operations should work.
# Using $(call) only.
####################################################################################################

function happy_path_using_call {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

\$(call bmakelib.dict.define,MY-DICT)
\$(call bmakelib.dict.put,MY-DICT,key1,value1)
\$(call bmakelib.dict.put,MY-DICT,key2,value2)

a-target :
	@echo \$(call bmakelib.dict.get,MY-DICT,key1)
	@echo \$(call bmakelib.dict.get,MY-DICT,key2)
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
value1
value2
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# When a dictionary is defined, happy-path put and get operations should work.
# Using target dependencies only.
####################################################################################################

function happy_path_using_target_dependency {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

dict-setup-target : bmakelib.dict.define( MY-DICT )
dict-setup-target : bmakelib.dict.put( MY-DICT,key1,value1  )
dict-setup-target : bmakelib.dict.put( MY-DICT,key2,value2  )

a-target : dict-setup-target
a-target :
	@echo \$(call bmakelib.dict.get,MY-DICT,key1)
	@echo \$(call bmakelib.dict.get,MY-DICT,key2)
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
value1
value2
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# When a dictionary is defined, `put` should reject a blank key.
# It should also raise an $(error) if `conf.dict.error-if-blank-key` is set to yes.
####################################################################################################

function put_should_reject_blank_key_with_error_when_conf_is_set {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

\$(call bmakelib.dict.define,MY-DICT)
\$(call bmakelib.dict.put,MY-DICT,,value1)

a-target :
         ;
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
.+\*\*\*\s+bmakelib.dict: Key cannot be blank.\s+Stop.
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# When a dictionary is defined, `put` should accept a blank key with a $(warning) if
# `conf.dict.error-if-blank-key` is not set to yes.
####################################################################################################

function put_should_accept_blank_key_with_warning_when_conf_is_set {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

bmakelib.conf.dict.error-if-blank-key := no

\$(call bmakelib.dict.define,MY-DICT)
\$(call bmakelib.dict.put,MY-DICT,,value1)

a-target :
	@echo \$(call bmakelib.dict.get,MY-DICT,)
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
.+\s+bmakelib.dict: Using blank key.
value1
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# The default value of `conf.dict.error-if-blank-key` is yes.
####################################################################################################

function default_value_of_conf_dict_error_if_blank_key_is_yes {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

a-target :
	@echo \$(bmakelib.conf.dict.error-if-blank-key)
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
yes
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# When a dictionary is defined, `put` should reject a blank value and raise an $(error) if
# `bmakelib.conf.dict.error-if-blank-value` is set to yes.
####################################################################################################

function put_should_reject_blank_value_with_error_when_conf_is_set {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

bmakelib.conf.dict.error-if-blank-value := yes

\$(call bmakelib.dict.define,MY-DICT)
\$(call bmakelib.dict.put,MY-DICT,key1,)

a-target :
	@:
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
.+\*\*\*\s+bmakelib.dict: Value cannot be blank.\s+Stop.
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# When a dictionary is defined, `put` should accept a blank value and raise a $(warning )if
# `bmakelib.conf.dict.error-if-blank-value` is not set to yes.
####################################################################################################

function put_should_accept_blank_value_with_warning_when_conf_is_set {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

\$(call bmakelib.dict.define,MY-DICT)
\$(call bmakelib.dict.put,MY-DICT,key1,)

a-target :
	@echo \'\$(call bmakelib.dict.get,MY-DICT,key1)\'
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
.+\s+bmakelib.dict: Using blank value.
''
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################
# The default value of `conf.dict.error-if-blank-value` is no.
####################################################################################################

function default_value_of_conf_dict_error_if_blank_value_is_no {
  local test_case_name=${FUNCNAME[0]}
  local actual_value_filename=${test_case_name}.actual.log
  bmakelib.test.cat <<EOF > Makefile
SHELL := /usr/bin/env bash
include \$(bmakelib.ROOT)/bmakelib.mk

a-target :
	@echo \$(bmakelib.conf.dict.error-if-blank-value)
EOF

  make a-target > $actual_value_filename 2>&1

  local expexted_pattern_filename=${test_case_name}.expected.pattern
  bmakelib.test.cat <<EOF > $expexted_pattern_filename
make.+Entering.+
no
make.+Leaving.+
EOF

  bmakelib.test.assert_matches $test_case_name $actual_value_filename $expexted_pattern_filename \
    || return 1
}

####################################################################################################

test_cases=( happy_path_using_call
             happy_path_using_target_dependency
             put_should_reject_blank_key_with_error_when_conf_is_set
             put_should_accept_blank_key_with_warning_when_conf_is_set
             default_value_of_conf_dict_error_if_blank_key_is_yes
             put_should_reject_blank_value_with_error_when_conf_is_set
             put_should_accept_blank_value_with_warning_when_conf_is_set
             default_value_of_conf_dict_error_if_blank_value_is_no )

test_case_name=''	# mutated in the for loop
test_suite_status=0	# mutated in the for loop
for test_case in ${test_cases[@]}; do
  test_case_name=$test_case
  if ! bmakelib.test.run_test_case $test_case; then
    test_suite_status=1
  fi
done

exit $test_suite_status
